CANVAS_ITEMS = [
    {
        "id": "c1",
        "type": "insight",
        "title": "Welcome",
        "item_description": "High-level welcome insight tile for canvas readiness.",
        "content": "100% of users find this canvas useful.",
        "col_span": 4,
        "row_span": 1,
        "variant": "success",
    },
    {
        "id": "c2",
        "type": "insight",
        "title": "Welcome",
        "item_description": "Caution-level insight showing moderate user value.",
        "content": "20% of users find this canvas useful.",
        "col_span": 4,
        "row_span": 1,
        "variant": "caution",
    },
    {
        "id": "c3",
        "type": "insight",
        "title": "Welcome",
        "item_description": "Danger-level insight showing low user value.",
        "content": "0% of users find this canvas useful.",
        "col_span": 6,
        "row_span": 1,
        "variant": "danger",
    },
]
